### PR TITLE
remove duplicate key ConnectTimeout StrictHostKeyChecking

### PR DESCRIPTION
**Pull request by ahelal**

### CODE REVIEW

**Comment by ahelal** [comment]
Hi just remove duplicate keys for ansible v2 warning msg

**Comment by farridav** [comment]
Thanks, a Fairly trivial change so will try to get it in quickly, `ConnectTimeout` had values of both `30` and `0`, have you removed the one that preserves backward compatibility ?

**Comment by soupdiver** [comment]
LGTM

**Comment by ahelal** [comment]
Any update ?

**Comment by farridav** [comment]
I had asked a question back on 14 Jan and was awaiting a reply, but the change is pretty sane anyhow, so happy top merge now

**Pull request merged**
